services:
  foundry:
    container_name: ${APP_FOUNDRY_NAME}_v${APP_FOUNDRY_VERSION}
    environment:
      FOUNDRY_ROUTE_PREFIX: foundry/v${APP_FOUNDRY_VERSION}
      FOUNDRY_HOSTNAME: ${APP_URL_SUBDOMAIN}${APP_URL_DOMAIN}
      FOUNDRY_PROXY_SSL: true
      FOUNDRY_PROXY_PORT: 443
      FOUNDRY_USERNAME: ${APP_FOUNDRY_USERNAME}
      FOUNDRY_PASSWORD: ${APP_FOUNDRY_PASSWORD}
      FOUNDRY_LICENSE_KEY: ${APP_FOUNDRY_LICENSE_KEY}
      FOUNDRY_ADMIN_KEY: ${APP_FOUNDRY_ADMIN_KEY}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 60s
      test: ["CMD-SHELL", "curl -f http://localhost:30000/$$FOUNDRY_ROUTE_PREFIX"]
      timeout: 5s
    image: felddy/foundryvtt:${APP_FOUNDRY_VERSION}
    labels:
      homepage.server: ${APP_LABEL_HOMEPAGE_SERVER:-docker-server}
      homepage.group: ${APP_FOUNDRY_NAME}
      homepage.name: ${APP_FOUNDRY_LABEL_HOMEPAGE_NAME}
      homepage.icon: ${APP_FOUNDRY_LABEL_HOMEPAGE_ICON}
      homepage.href: https://${APP_URL_SUBDOMAIN}${APP_URL_DOMAIN}/foundry/v${APP_FOUNDRY_VERSION}
    networks:
      - proxy-net
    restart: unless-stopped
    volumes:
      - ${APP_PATH_DATA}/foundry/v${APP_FOUNDRY_VERSION}:/data

networks:
  proxy-net:
    external: true