services:
  romm-db:
    container_name: ${APP_ROMM_NAME}_db
    environment:
      POSTGRES_DB: ${APP_ROMM_DB_DATABASE}
      POSTGRES_USER: ${APP_ROMM_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_ROMM_DB_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 15s
      test: ["CMD", "pg_isready", "-U", "${APP_ROMM_DB_USERNAME}", "-d", "${APP_ROMM_DB_DATABASE}"]
      timeout: 5s
    image: postgres:18
    networks:
      - default
    restart: unless-stopped
    user: 999:999
    volumes:
      - ${APP_PATH_DATA}/romm/postgres:/var/lib/postgresql

  romm-server:
    container_name: ${APP_ROMM_NAME}
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    environment:
      TZ: ${TZ}
      ROMM_DB_DRIVER: postgresql
      DB_HOST: romm-db
      DB_PORT: 5432
      DB_NAME: ${APP_ROMM_DB_DATABASE}
      DB_USER: ${APP_ROMM_DB_USERNAME}
      DB_PASSWD: ${APP_ROMM_DB_PASSWORD}
      ROMM_AUTH_SECRET_KEY: ${APP_ROMM_KEY}
      IGDB_CLIENT_ID: ${APP_ROMM_API_IGDB_CLIENTID}
      IGDB_CLIENT_SECRET: ${APP_ROMM_API_IGDB}
      RETROACHIEVEMENTS_API_KEY: ${APP_ROMM_API_RETROACHIEVEMENTS}
      STEAMGRIDDB_API_KEY: ${APP_ROMM_API_STEAMGRIDDB}
      HASHEOUS_API_ENABLED: true
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      timeout: 10s
    image: rommapp/romm:latest
    labels:
      homepage.server: ${APP_LABEL_HOMEPAGE_SERVER:-docker-server}
      homepage.group: ${APP_ROMM_NAME}
      homepage.name: ${APP_ROMM_LABEL_HOMEPAGE_NAME}
      homepage.icon: ${APP_ROMM_LABEL_HOMEPAGE_ICON}
      homepage.href: https://${APP_URL_SUBDOMAIN}${APP_URL_DOMAIN}
      homepage.widget.type: romm
      homepage.widget.url: http://${APP_ROMM_NAME}:8080
    networks:
      - proxy-net
      - default
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${APP_PATH_DATA}/romm/config:/romm/config
      - ${APP_PATH_DATA}/romm/assets:/romm/assets
      - ${APP_PATH_LIBRARY}/Games:/romm/library
      - resources:/romm/resources
      - redis_data:/redis-data

networks:
  proxy-net:
    external: true

volumes:
  resources:
  redis_data: