services:
  coder-db:
    container_name: ${APP_CODER_NAME}_db
    environment:
      POSTGRES_DB: ${APP_CODER_DB_DATABASE}
      POSTGRES_USER: ${APP_CODER_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_CODER_DB_PASSWORD}
    healthcheck:
      interval: 5s
      retries: 5
      test: ["CMD", "pg_isready", "-U", "${APP_CODER_DB_USERNAME}", "-d", "${APP_CODER_DB_DATABASE}"]
      timeout: 5s
    image: "postgres:17"
    networks:
      - default
    restart: unless-stopped
    user: 999:999
    volumes:
      - ${APP_PATH_DATA}/coder/postgres:/var/lib/postgresql/data

  coder:
    container_name: ${APP_CODER_NAME}
    depends_on:
      coder-db:
        condition: service_healthy
    environment:
      CODER_PG_CONNECTION_URL: postgresql://${APP_CODER_DB_USERNAME}:${APP_CODER_DB_PASSWORD}@${APP_CODER_NAME}_db/${APP_CODER_DB_DATABASE}?sslmode=disable
      CODER_HTTP_ADDRESS: 0.0.0.0:${APP_CODER_PORT:-7080}
      CODER_ACCESS_URL: https://${APP_URL_SUBDOMAIN}${APP_URL_DOMAIN}
      CODER_SESSION_SECRET: ${APP_CODER_SESSION_SECRET}
    group_add:
      - "999"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: ["CMD", "curl", "-f", "http://localhost:7080/healthz"]
      timeout: 10s
    image: ghcr.io/coder/coder:latest
    networks:
      - default
      - proxy-net
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_PATH_DATA}/coder/data:/home/coder

networks:
  proxy-net:
    external: true